### PR TITLE
Add python

### PR DESCRIPTION
**Pull request by Konfekt**
I suppose `test_...` is the standard rather than `..._test` in Go?

### CODE REVIEW

**Comment by arp242** [comment]
I was under the impression that most Python projects have test files in a different directory, rather than next to the implementation like Go does.

That is:

    project/foo.py             # Or project/project/foo.py
    project/tests/test_foo.py

I don't do much Python these days though.

**Comment by Konfekt** [comment]
Yes, me too. You are right. I'll go for that

**Comment by arp242** [comment]
Well, I don't know if that's really the (de-facto) standard – it was more of a question than anything else. I'm not really sure Python really has a standard in the same way that Go or .c/.h has(?)

**Comment by Konfekt** [comment]
It does not. I did not know Go has. Anyway, I think little harm is done by giving it a try, do something useful. That's how de facto standards arise. It's hard coded into https://github.com/kana/vim-altr/blob/master/autoload/altr.vim#L99

**Comment by arp242** [comment]
I merged it for now, thanks.

I think it may be possible to improve this by looking at parent directories. For example, most Python projects at $dayjob have all tests as `tests/test_XXX.py` in the top level. I don't work on this code myself by the way.

This also seems to be what projects like [requests] or [tomli] do.

So it probably makes sense to do something like:

	if tests/test_xxx.py exists → open
	dir = "."
	while not exists ./requirement.txt or setup.py or pyproject.toml
		dir += "/.."
		if at_root then break
		if dir + /tests/test_xxx.py exists → open
	done
	open tests/test_xxx.py (non-existing file)

Or something along those lines: search up the tree for test/test_xxx.py

[requests]: https://github.com/psf/requests
[tomli]: https://github.com/hukkin/tomli

**Comment by Konfekt** [comment]
This was meant this way, by looking for `tests` in the current work dir. https://github.com/arp242/switchy.vim/pull/7 fixes this.

**Comment by Konfekt** [comment]
> search up the tree for test/test_[xxx.py](http://xxx.py/)

#7 only implements it for the current work dir.
This code would look for a `tests` folder.

```vim
function! s:FindRoot(dir) abort
    let current_dir = a:dir
    while v:true
        if isdirectory(current_dir..s:slash..'tests')
            return current_dir..s:slash..'tests'
        endif
        let parent_dir = fnamemodify(current_dir, ':h')
        if current_dir ==# parent_dir
          return ''
        else
          let current_dir = parent_dir
        endif
    endwhile
    return ''
endfunction
```

**Pull request merged**
